### ISSUE TITLE
Give back the maintainer right

### ISSUE THREAD

**Issue by bashu** [adamcharnock/django-tz-detect#11]
Hi,

This repository seems to lack maintenance, I propose myself as a new maintainer.

Could you give me the right to push in your repository or just transfer it on my account in github?

Thank you

**Comment by adamcharnock** [comment]
Hi @bashu, you are absolutely right. It is something I may come back to in future (if a future client needs it), but I'd certainly be happy for you to take the reins.

I've just made you a collaborator.
