### ISSUE TITLE
Url patterns is deprecated

### ISSUE THREAD

**Issue by johndark** [adamcharnock/django-tz-detect#24]
Hi guys, just got in mine project (django 1.9.1):
[WARNING:py.warnings]**[__init__.py:84]: site-packages\tz_detect\urls.py:8: RemovedInDjango110Warning: django.conf.urls.pat
terns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^set/$', SetOffsetView.as_view(), name="tz_detect__set"),

as I see in the code it's:
urlpatterns = patterns('',...)

**Comment by adamcharnock** [comment]
Thanks for the issue @johndark! I'm not going to have time to take a look at this for a bit, but would gladly take a pull request.

+1's welcome.

**Comment by bashu** [comment]
try ``pip install -U django-tz-detect``
