### ISSUE TITLE
Empty template block. Bug or a feature?

### ISSUE THREAD

**Issue by elonen** [adamcharnock/django-tz-detect#35]
I'm running django-tz-detect 0.2.8 on Django 1.9.13 . Attempting to include tz_detect in the template as follows...

```
{% extends "admin/base_site.html" %}
{% block extrahead %}
 <!-- BEGIN django_tz_detect -->
 {% load tz_detect %}
 {% tz_detect %}
 <!-- END django_tz_detect -->
{% endblock %}
```
...Chrome's view source shows an empty block (but no errors):

```
<!-- BEGIN django_tz_detect -->





<!-- END django_tz_detect -->
```

Why might this be? The odd thing is, timezone seems correct anyway.

**Comment by elonen** [comment]
Oh, I think I figured it out.
It only outputs the javascript until it has determined the timezone and then hides it, right?

**Comment by bashu** [comment]
@elonen absolutely! as you can see in https://github.com/adamcharnock/django-tz-detect/blob/develop/tz_detect/templates/tz_detect/detector.html and https://github.com/adamcharnock/django-tz-detect/blob/develop/tz_detect/templatetags/tz_detect.py
