### ISSUE TITLE
django-tz-detect doesn't work in production.

### ISSUE THREAD

**Issue by tanjyeyee** [adamcharnock/django-tz-detect#43]
So I've tested it locally, and it works.
But when I moved it to production, it doesn't work.

All my times are shown in UTC (server time).

I've viewed source to make sure that the Javascript snippet is included during the initial session, but any datetime is still shown in UTC.

Any help would be appreciated.

**Comment by bashu** [comment]
@tanjyeyee project sources?

**Comment by tanjyeyee** [comment]
> @tanjyeyee how can I reproduce it?

Hi bashu, what I did was to query some transactions from the Stripe API, which lists its transactions in UTC timestamp. So in my views.py:

```
charge = stripe.Charge.retrieve('ch_1EMXx9CCIFXs3d6gzBAuJMCZ')

datetime = datetime.fromtimestamp(charge.created)
```

Then in my template:

`Time: {{ datetime|date:'j M Y, g:i a' }}`

Unfortunately the date time shown in the template is UTC time. I'm in PDT, so that's 7 hours behind.

Interestingly, I've tested in my template just this:

`Time: {{ now 'M jS, Y, g:i a' }}`

And it shows the time in PDT, even though my server time is definitely UTC.
So I could get it to work under certain circumstances.

Am I missing anything?

**Comment by bashu** [comment]
@tanjyeyee still an issue? something tells me ``{{ datetime }}`` is not time zone aware, either convert it like this:
```python
import pytz

datetime = datetime.fromtimestamp(charge.created).replace(tzinfo=pytz.UTC)
```
or in template:
```html+django
{{ datetime|localtime|date:'j M Y, g:i a' }}
```

for ref: https://docs.djangoproject.com/en/1.11/topics/i18n/timezones/#time-zone-aware-output-in-templates

**Comment by tanjyeyee** [comment]
@bashu Wow. And just like that, it worked. All I had to do was to make the datetime object timezone-aware, as per your suggestion. Thanks a lot! Consider this issue solved.
