### ISSUE TITLE
Wrong TZ detected for sessions that cross DST change

### ISSUE THREAD

**Issue by ktosiek** [adamcharnock/django-tz-detect#47]
As the TZ guessing is only based on offset, and the guessed TZ is never saved, the same offset will be used after the user moved into daylight saving. This causes existing sessions to change current timezone.

**Comment by K-MTG** [comment]
I noticed the same behavior. I'm in PST so 
```
"offset=" + (new Date).getTimezoneOffset()
"offset=480"
```

My server backend is in UTC. DST at PST doesn't occur until 2AM tomorrow but since the server backend timezone crossed over. I'm getting the timezone listed as AKST on my app.

**Comment by ktosiek** [comment]
Fixed by #63, closing.
