### ISSUE TITLE
How can i access this in views.py. 

### ISSUE THREAD

**Issue by muhamedsuhail** [adamcharnock/django-tz-detect#48]
I can use this in templates. But for storing time to database I need to access it in views.py. How can i do that?

**Comment by bashu** [comment]
@muhamedsuhail I don't understand your question? access what?

**Comment by muhamedsuhail** [comment]
If I need to display the current time in the template I use {% load tz_detect %}..and just call {% now "jS F Y H: i" %}. I am using an auto_add_true field for the time in my models.py .How can I make that auto_add time to be from tz_detect. It does not detect timezone in the auto_add field. It just adds UTC to the database.

**Comment by freQuensy23-coder** [comment]
I think his question was: Is it possible to somehow get the user's time zone while processing a request in a view.py?

**Comment by freQuensy23-coder** [comment]
I think that you can user ```request.GET.get('timezone')```

**Comment by bashu** [comment]
or you can use `timezone.now()` like you did it before

**Comment by bashu** [comment]
to @muhamedsuhail storing in UTC is right way, you should convert it to local time in views/templates. if you want to store end user timezone, use https://pypi.org/project/django-timezone-field/ and store detected timezone here, for reference https://docs.djangoproject.com/en/3.2/ref/utils/#module-django.utils.timezone
