### ISSUE TITLE
Release for Django 4.0 support?

### ISSUE THREAD

**Issue by mblayman** [adamcharnock/django-tz-detect#51]
Hello tz_detect devs, it looks like PR #50 merged a change to fix an import issue for Django 4.0.

Any chance that a 0.4.0 release could be cut soon? This could unblock anyone who wants to upgrade to Django 4.0 (selfishly, like me https://github.com/mblayman/homeschool/runs/4878940880?check_suite_focus=true)

It appears that CI no longer runs for this repo. Would running CI on GitHub Actions unblock this project from a new release?

**Comment by adamcharnock** [comment]
Thank you for the remninder @mblayman!

@bashu – how do we do releases again? I'd do it, but I think the release process has changed now and I'm not familiar with it.

**Comment by danielsjf** [comment]
Also interested in this release in order to upgrade to Django 4.0+.

**Comment by mblayman** [comment]
@bashu, thanks for merging my PR. The PR inadvertently closed this issue because I happened to use the phrase "resolve #51" in a sentence. Can you reopen this because there isn't a 4.0 compatible release yet?
