### ISSUE TITLE
Detect wrong timezone when we have daylight saving time.

### ISSUE THREAD

**Issue by sunshineo** [adamcharnock/django-tz-detect#9]
Hi everyone,

I am located in Seattle. We have PST Pacific standard time, offset UTC - 8 hours. http://www.timeanddate.com/library/abbreviations/timezones/na/pst.html
However at this time of the year, we have PDT Pacific daylight time, offset UTC -7 hours.

My browser knows this, so your JS code post the correct offset integer 420. Tested in my browser as below
>(new Date()).getTimezoneOffset()
>420

However, after the post reach the server side, the timezone being detected is wrong.
>>> from tz_detect.utilities import offset_to_timezone
>>> tz = offset_to_timezone(int(420))
>>> print tz
America/Phoenix

Phoenix Arizona does not have daylight saving and they are having the same offset.

>>> test_time = datetime.strptime("2014/05/21 11:00", "%Y/%m/%d %H:%M")
>>> test_time = test_time.replace(tzinfo=tz)
>>> print test_time.strftime("%Y/%m/%d %H:%M %Z")
2014/05/21 11:00 MST

This shows that the America/Phoenix timezone is the MST Mountain standard time
http://www.timeanddate.com/library/abbreviations/timezones/na/mst.html

Any idea on how to solve this problem?

--Gordon

**Comment by bashu** [comment]
is this still an issue?

**Comment by sunshineo** [comment]
Not to me.
